services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: biblioteca-sql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourPassword123!
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P $${SA_PASSWORD} -No -Q 'SELECT 1' -C || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 10
    volumes:
      - sqlserver_data:/var/opt/mssql

  webapi:
    build:
      context: .
      dockerfile: WebApi/Web/Dockerfile
    container_name: biblioteca-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=biblioteca;User Id=sa;Password=YourPassword123!;TrustServerCertificate=True;
    ports:
      - "8080:8080"
    depends_on:
      sqlserver:
        condition: service_healthy

volumes:
  sqlserver_data:

